### ISSUE TITLE
[Feature Request] custom fallback rules

### ISSUE THREAD

**Issue by KevinZonda** [Limit-LAB/r18#5]
# 🚀 Feature Request

Hiya, I just wonder is there any possible solution for fallbacking? E.g. if Chinese simplified not available, then fallback to Chinese Traditional then English. Thx

**Comment by ho-229** [comment]
This feature is implemented: #1 
So you mean custom fallback rules?

**Comment by KevinZonda** [comment]
yes

24 Dec 2022, 03:49 by ***@***.***:
